[[redirects]]
  from = "/api/posts"
  to = "https://myprisma.netlify.app/.netlify/functions/posts"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[redirects]]
  from = "/api/post"
  to = "https://myprisma.netlify.app/.netlify/functions/post"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"